version: '1'
services:
    sample-app-mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
        command: mongos --configdb sample-app-mongodb-config
    sample-app-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    sample-app-mongodb-config:
        image: mongo:3.4.8
        container_name: sample-app-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
